AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for storing Docker images of the Wisdom Quotes API

Resources:
  WisdomQuotesECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: wisdom-quotes-api-dev
      ImageScanningConfiguration:
        scanOnPush: true
      Tags:
        - Key: Environment
          Value: dev
        - Key: Project
          Value: wisdom

Outputs:
  ECRRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt WisdomQuotesECR.RepositoryUri
    Export:
      Name: WisdomQuotesECRUri


